name: Validate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  UV_CACHE_DIR: ~/.cache/uv
  CUDA_KEYRING_VERSION: 1.1-1
  CUDA_TOOLKIT_VERSION: 13-0

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up uv and Python
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0

      - name: Cache uv
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          path: ${{ env.UV_CACHE_DIR }}

      - name: Cache CUDA apt packages
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          key: apt-cuda-${{ env.CUDA_TOOLKIT_VERSION }}
          path: /var/cache/apt/archives

      - name: Install CUDA toolkit
        run: |
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_${CUDA_KEYRING_VERSION}_all.deb
          sudo dpkg -i cuda-keyring_${CUDA_KEYRING_VERSION}_all.deb
          sudo apt-get update
          sudo apt-get install -y cuda-toolkit-${CUDA_TOOLKIT_VERSION}

      - name: Check UV lock file
        run: uv lock --locked

      - name: Install
        run: uv sync --frozen

      - name: Check format (C++)
        run: |
          sudo apt-get install -y clang-format
          find src \( -name "*.cpp" -o -name "*.h" -o -name "*.cu" \) | xargs -r clang-format --dry-run --Werror

      - name: Check format (Python)
        run: uv run --no-sync ruff format --check

      - name: Check lint
        run: uv run --no-sync ruff check

      - name: Run tests
        run: uv run --no-sync pytest ./src/tests/ -v
